// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWe50l_9OrtW2eOH6r-isBGnGLaQ0eSeo',
    appId: '1:623171805605:web:a10294155df198499a884c',
    messagingSenderId: '623171805605',
    projectId: 'fir-demo-4bf75',
    authDomain: 'fir-demo-4bf75.firebaseapp.com',
    storageBucket: 'fir-demo-4bf75.appspot.com',
    measurementId: 'G-SX38HQB3RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-IIp6E_cVegYxKCIKVuDpO0y11_8CM1M',
    appId: '1:623171805605:android:18019a22f873a59e9a884c',
    messagingSenderId: '623171805605',
    projectId: 'fir-demo-4bf75',
    storageBucket: 'fir-demo-4bf75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwgw6XofxEJyBBp2sOp5ad4iTdUMfiEaQ',
    appId: '1:623171805605:ios:c16c5cb3e96a7d5a9a884c',
    messagingSenderId: '623171805605',
    projectId: 'fir-demo-4bf75',
    storageBucket: 'fir-demo-4bf75.appspot.com',
    iosClientId: '623171805605-h42vi68lr19277hlpkkop7qh5te43qbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firecore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwgw6XofxEJyBBp2sOp5ad4iTdUMfiEaQ',
    appId: '1:623171805605:ios:026321d0cb2be5749a884c',
    messagingSenderId: '623171805605',
    projectId: 'fir-demo-4bf75',
    storageBucket: 'fir-demo-4bf75.appspot.com',
    iosClientId: '623171805605-sa0sq2cqdv6fomsscn0gh9lg1vtg6ji5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firecore.RunnerTests',
  );
}
